//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnFinalIlds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuyerMaster()
        {
            this.BuyerFaceForProducts = new HashSet<BuyerFaceForProduct>();
            this.BuyerProducts = new HashSet<BuyerProduct>();
            this.BuyerProductSchedules = new HashSet<BuyerProductSchedule>();
            this.CommissionMasters = new HashSet<CommissionMaster>();
            this.CommonLeads = new HashSet<CommonLead>();
            this.TransferLogs = new HashSet<TransferLog>();
        }
    
        public int ID { get; set; }
        public string BuyerName { get; set; }
        public string BuyerAddress { get; set; }
        public string BuyerPincode { get; set; }
        public string BuyerPocName { get; set; }
        public string BuyerContactNumber { get; set; }
        public string BuyerPocContactNumber { get; set; }
        public string BuyerType { get; set; }
        public string IcoNo { get; set; }
        public string BuyerEmail { get; set; }
        public string FcaNo { get; set; }
        public Nullable<System.DateTime> IcoExpDate { get; set; }
        public string CompanyRegistrationNo { get; set; }
        public int State { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int DeleteStatus { get; set; }
        public Nullable<bool> IsSendNotifyMail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerFaceForProduct> BuyerFaceForProducts { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerProduct> BuyerProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerProductSchedule> BuyerProductSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommissionMaster> CommissionMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonLead> CommonLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferLog> TransferLogs { get; set; }
    }
}
