//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnFinalIlds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerProductScheduleSlab
    {
        public int ID { get; set; }
        public int BuyerProductScheduleId { get; set; }
        public int ProductSlabId { get; set; }
        public int Demand { get; set; }
        public double Price { get; set; }
        public int PaymentMode { get; set; }
        public double Budget { get; set; }
        public int ActiveState { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int DeleteStatus { get; set; }
        public int DailyDemand { get; set; }
        public int Weightage { get; set; }
    
        public virtual BuyerProductSchedule BuyerProductSchedule { get; set; }
        public virtual ProductSlab ProductSlab { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
