//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnFinalIlds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerProductSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuyerProductSchedule()
        {
            this.BuyerProductScheduleDays = new HashSet<BuyerProductScheduleDay>();
            this.BuyerProductScheduleSlabs = new HashSet<BuyerProductScheduleSlab>();
            this.BuyerProductScheduleTimes = new HashSet<BuyerProductScheduleTime>();
            this.TransferLogs = new HashSet<TransferLog>();
        }
    
        public int ID { get; set; }
        public int BuyerMasterId { get; set; }
        public int ProductMasterId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public int TimePeriod { get; set; }
        public int ActiveState { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int DeleteStatus { get; set; }
        public int Demand { get; set; }
        public int DailyDemand { get; set; }
        public int PaymentMode { get; set; }
    
        public virtual BuyerMaster BuyerMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerProductScheduleDay> BuyerProductScheduleDays { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerProductScheduleSlab> BuyerProductScheduleSlabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerProductScheduleTime> BuyerProductScheduleTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferLog> TransferLogs { get; set; }
    }
}
