//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnFinalIlds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionMaster
    {
        public int ID { get; set; }
        public double BasePrice { get; set; }
        public int BuyerId { get; set; }
        public int ProductId { get; set; }
        public double Percentage { get; set; }
        public double RejectionPercentage { get; set; }
    
        public virtual BuyerMaster BuyerMaster { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
    }
}
