//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnFinalIlds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonLead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommonLead()
        {
            this.ASULeadLogs = new HashSet<ASULeadLog>();
            this.ASULeads = new HashSet<ASULead>();
            this.CommonLeadLogs = new HashSet<CommonLeadLog>();
            this.CorporateHealthLeadLogs = new HashSet<CorporateHealthLeadLog>();
            this.CorporateHealthLeads = new HashSet<CorporateHealthLead>();
            this.DebtLeadLogs = new HashSet<DebtLeadLog>();
            this.DebtLeads = new HashSet<DebtLead>();
            this.EquityReleaseLeadLogs = new HashSet<EquityReleaseLeadLog>();
            this.EquityReleaseLeads = new HashSet<EquityReleaseLead>();
            this.HealthLeadLogs = new HashSet<HealthLeadLog>();
            this.HealthLeads = new HashSet<HealthLead>();
            this.IncomeProtectionLeadLogs = new HashSet<IncomeProtectionLeadLog>();
            this.IncomeProtectionLeads = new HashSet<IncomeProtectionLead>();
            this.InjuryClaimLeadLogs = new HashSet<InjuryClaimLeadLog>();
            this.InjuryClaimLeads = new HashSet<InjuryClaimLead>();
            this.LeadEmailRequests = new HashSet<LeadEmailRequest>();
            this.LifeLeadLogs = new HashSet<LifeLeadLog>();
            this.LifeLeads = new HashSet<LifeLead>();
            this.LoanLeads = new HashSet<LoanLead>();
            this.LogBookLoanLeadLogs = new HashSet<LogBookLoanLeadLog>();
            this.LogBookLoanLeads = new HashSet<LogBookLoanLead>();
            this.PensionLeadLogs = new HashSet<PensionLeadLog>();
            this.PensionLeads = new HashSet<PensionLead>();
            this.PPILeadLogs = new HashSet<PPILeadLog>();
            this.PPILeads = new HashSet<PPILead>();
            this.PrepaidFuneralLeadLogs = new HashSet<PrepaidFuneralLeadLog>();
            this.PrepaidFuneralLeads = new HashSet<PrepaidFuneralLead>();
            this.SolarLeadLogs = new HashSet<SolarLeadLog>();
            this.SolarLeads = new HashSet<SolarLead>();
            this.TransferLogs = new HashSet<TransferLog>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string City { get; set; }
        public string Postcode { get; set; }
        public string WorkPhone { get; set; }
        public string HomePhone { get; set; }
        public string Address1 { get; set; }
        public string Email { get; set; }
        public int WebsiteMasterId { get; set; }
        public string ProductName { get; set; }
        public int ProductMasterId { get; set; }
        public string IpAddress { get; set; }
        public string Source { get; set; }
        public string MatchType { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> LeadStatus { get; set; }
        public Nullable<int> DNC { get; set; }
        public string SourceUid { get; set; }
        public string PostcodeOutWard { get; set; }
        public string PostcodeInWard { get; set; }
        public int OrganizationMasterId { get; set; }
        public string OrganizationHashCode { get; set; }
        public string OperatorName { get; set; }
        public int ContactTime { get; set; }
        public int LeadCategory { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int DeleteStatus { get; set; }
        public Nullable<int> BuyerMaster_ID { get; set; }
        public string OperatorSpecificComments { get; set; }
        public Nullable<int> LeadType { get; set; }
        public bool Opt { get; set; }
        public string LeadComment { get; set; }
        public double NotifyPrice { get; set; }
        public string AdditionalInformation { get; set; }
        public string UserAgent { get; set; }
        public string Query { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASULeadLog> ASULeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASULead> ASULeads { get; set; }
        public virtual BuyerMaster BuyerMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonLeadLog> CommonLeadLogs { get; set; }
        public virtual OrganizationMaster OrganizationMaster { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        public virtual WebsiteMaster WebsiteMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorporateHealthLeadLog> CorporateHealthLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorporateHealthLead> CorporateHealthLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebtLeadLog> DebtLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebtLead> DebtLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquityReleaseLeadLog> EquityReleaseLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquityReleaseLead> EquityReleaseLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthLeadLog> HealthLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthLead> HealthLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomeProtectionLeadLog> IncomeProtectionLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomeProtectionLead> IncomeProtectionLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InjuryClaimLeadLog> InjuryClaimLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InjuryClaimLead> InjuryClaimLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadEmailRequest> LeadEmailRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LifeLeadLog> LifeLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LifeLead> LifeLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanLead> LoanLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogBookLoanLeadLog> LogBookLoanLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogBookLoanLead> LogBookLoanLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PensionLeadLog> PensionLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PensionLead> PensionLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPILeadLog> PPILeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPILead> PPILeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrepaidFuneralLeadLog> PrepaidFuneralLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrepaidFuneralLead> PrepaidFuneralLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolarLeadLog> SolarLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolarLead> SolarLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferLog> TransferLogs { get; set; }
    }
}
