//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnFinalIlds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporateHealthLeadLog
    {
        public int ID { get; set; }
        public int CorporateHealthLeadId { get; set; }
        public int Stage { get; set; }
        public int CommonLeadId { get; set; }
        public System.DateTime Dob { get; set; }
        public Nullable<int> Age { get; set; }
        public int Period { get; set; }
        public int PremiumTypeId { get; set; }
        public int InsuranceTypeId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyPostCode { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyAddress { get; set; }
        public int EmployeeNumber { get; set; }
        public bool ExistingPolicy { get; set; }
        public string PartnerGender { get; set; }
        public int CorporateCoverTypeHealth { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int DeleteStatus { get; set; }
    
        public virtual CommonLead CommonLead { get; set; }
        public virtual CorporateHealthLead CorporateHealthLead { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
