//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnFinalIlds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquityReleaseLead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquityReleaseLead()
        {
            this.EquityReleaseLeadLogs = new HashSet<EquityReleaseLeadLog>();
        }
    
        public int ID { get; set; }
        public int LeadId { get; set; }
        public int Age { get; set; }
        public System.DateTime Dob { get; set; }
        public int HomeValue { get; set; }
        public Nullable<int> OutstandingMortgageValue { get; set; }
        public Nullable<int> AgeType { get; set; }
        public Nullable<int> EquityType { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int DeleteStatus { get; set; }
    
        public virtual CommonLead CommonLead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquityReleaseLeadLog> EquityReleaseLeadLogs { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
