//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnFinalIlds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogBookLoanLeadLog
    {
        public int ID { get; set; }
        public int LogBookLoanLeadId { get; set; }
        public int Stage { get; set; }
        public int CommonLeadId { get; set; }
        public int Amount { get; set; }
        public string NumberPlate { get; set; }
        public int CurrentMileage { get; set; }
        public bool ClearOfFinance { get; set; }
        public int LogBookLoanCountryResidence { get; set; }
        public string ContactTime { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public int CarRegistrationYear { get; set; }
        public System.DateTime Dob { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int DeleteStatus { get; set; }
    
        public virtual CommonLead CommonLead { get; set; }
        public virtual LogBookLoanLead LogBookLoanLead { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
