//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnFinalIlds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationProductAccess
    {
        public int ID { get; set; }
        public int OrganizationMasterId { get; set; }
        public int ProductMasterId { get; set; }
    
        public virtual OrganizationMaster OrganizationMaster { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
    }
}
