//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnFinalIlds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PensionLead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PensionLead()
        {
            this.PensionLeadLogs = new HashSet<PensionLeadLog>();
        }
    
        public int ID { get; set; }
        public int LeadId { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public int Age { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<int> PersonalPensionType { get; set; }
        public Nullable<int> PensionPremiumType { get; set; }
        public int PensionValue { get; set; }
        public Nullable<int> PensionType { get; set; }
        public Nullable<int> PensionAccessFund { get; set; }
        public int ExistPensions { get; set; }
        public string PensionTypeOther { get; set; }
        public bool IsCurrentlyPayingMoney { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int DeleteStatus { get; set; }
        public int TotalPensionValue { get; set; }
    
        public virtual CommonLead CommonLead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PensionLeadLog> PensionLeadLogs { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
