//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnFinalIlds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PensionLeadLog
    {
        public int ID { get; set; }
        public int PensionLeadId { get; set; }
        public int Stage { get; set; }
        public int CommonLeadId { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public int Age { get; set; }
        public System.DateTime Dob { get; set; }
        public int PersonalPensionType { get; set; }
        public int PensionPremiumType { get; set; }
        public int PensionValue { get; set; }
        public int PensionType { get; set; }
        public int PensionAccessFund { get; set; }
        public int ExistPensions { get; set; }
        public string PensionTypeOther { get; set; }
        public bool IsCurrentlyPayingMoney { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int DeleteStatus { get; set; }
    
        public virtual CommonLead CommonLead { get; set; }
        public virtual PensionLead PensionLead { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
