//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnFinalIlds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteVisitor
    {
        public int ID { get; set; }
        public int SiteId { get; set; }
        public string IpAddress { get; set; }
        public string UserAgent { get; set; }
        public System.DateTime GeneratedDate { get; set; }
    
        public virtual WebsiteMaster WebsiteMaster { get; set; }
    }
}
