//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnFinalIlds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMaster()
        {
            this.ASULeadLogs = new HashSet<ASULeadLog>();
            this.ASULeads = new HashSet<ASULead>();
            this.BuyerFaceForProducts = new HashSet<BuyerFaceForProduct>();
            this.BuyerMasters = new HashSet<BuyerMaster>();
            this.BuyerProductLeadCategories = new HashSet<BuyerProductLeadCategory>();
            this.BuyerProductLeadTypes = new HashSet<BuyerProductLeadType>();
            this.BuyerProducts = new HashSet<BuyerProduct>();
            this.BuyerProductScheduleDays = new HashSet<BuyerProductScheduleDay>();
            this.BuyerProductSchedules = new HashSet<BuyerProductSchedule>();
            this.BuyerProductScheduleSlabs = new HashSet<BuyerProductScheduleSlab>();
            this.BuyerProductScheduleTimes = new HashSet<BuyerProductScheduleTime>();
            this.CommonLeadLogs = new HashSet<CommonLeadLog>();
            this.CommonLeads = new HashSet<CommonLead>();
            this.CorporateHealthLeadLogs = new HashSet<CorporateHealthLeadLog>();
            this.CorporateHealthLeads = new HashSet<CorporateHealthLead>();
            this.DebtLeadLogs = new HashSet<DebtLeadLog>();
            this.DebtLeads = new HashSet<DebtLead>();
            this.EmailRequests = new HashSet<EmailRequest>();
            this.EquityReleaseLeadLogs = new HashSet<EquityReleaseLeadLog>();
            this.EquityReleaseLeads = new HashSet<EquityReleaseLead>();
            this.HealthLeadLogs = new HashSet<HealthLeadLog>();
            this.HealthLeads = new HashSet<HealthLead>();
            this.IncomeProtectionLeadLogs = new HashSet<IncomeProtectionLeadLog>();
            this.IncomeProtectionLeads = new HashSet<IncomeProtectionLead>();
            this.InjuryClaimLeadLogs = new HashSet<InjuryClaimLeadLog>();
            this.InjuryClaimLeads = new HashSet<InjuryClaimLead>();
            this.LeadEmailRequests = new HashSet<LeadEmailRequest>();
            this.LifeLeadLogs = new HashSet<LifeLeadLog>();
            this.LifeLeads = new HashSet<LifeLead>();
            this.LoanLeadLogs = new HashSet<LoanLeadLog>();
            this.LoanLeads = new HashSet<LoanLead>();
            this.LogBookLoanLeadLogs = new HashSet<LogBookLoanLeadLog>();
            this.LogBookLoanLeads = new HashSet<LogBookLoanLead>();
            this.MortgageLeadLogs = new HashSet<MortgageLeadLog>();
            this.MortgageLeads = new HashSet<MortgageLead>();
            this.PensionLeadLogs = new HashSet<PensionLeadLog>();
            this.PensionLeads = new HashSet<PensionLead>();
            this.PPILeadLogs = new HashSet<PPILeadLog>();
            this.PPILeads = new HashSet<PPILead>();
            this.PrepaidFuneralLeadLogs = new HashSet<PrepaidFuneralLeadLog>();
            this.PrepaidFuneralLeads = new HashSet<PrepaidFuneralLead>();
            this.ProductMasters = new HashSet<ProductMaster>();
            this.ProductSlabs = new HashSet<ProductSlab>();
            this.SlabDefinitions = new HashSet<SlabDefinition>();
            this.SolarLeadLogs = new HashSet<SolarLeadLog>();
            this.SolarLeads = new HashSet<SolarLead>();
            this.SuppressionDetails = new HashSet<SuppressionDetail>();
            this.Tokens = new HashSet<Token>();
            this.TransferLogs = new HashSet<TransferLog>();
            this.UserRoles = new HashSet<UserRole>();
            this.WebsiteMasters = new HashSet<WebsiteMaster>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Verificationcode { get; set; }
        public bool EmailVerified { get; set; }
        public string CompanyName { get; set; }
        public string Password { get; set; }
        public int State { get; set; }
        public int OrganizationMasterId { get; set; }
        public System.DateTime GeneratedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASULeadLog> ASULeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASULead> ASULeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerFaceForProduct> BuyerFaceForProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerMaster> BuyerMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerProductLeadCategory> BuyerProductLeadCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerProductLeadType> BuyerProductLeadTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerProduct> BuyerProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerProductScheduleDay> BuyerProductScheduleDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerProductSchedule> BuyerProductSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerProductScheduleSlab> BuyerProductScheduleSlabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerProductScheduleTime> BuyerProductScheduleTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonLeadLog> CommonLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonLead> CommonLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorporateHealthLeadLog> CorporateHealthLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorporateHealthLead> CorporateHealthLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebtLeadLog> DebtLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebtLead> DebtLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailRequest> EmailRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquityReleaseLeadLog> EquityReleaseLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquityReleaseLead> EquityReleaseLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthLeadLog> HealthLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthLead> HealthLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomeProtectionLeadLog> IncomeProtectionLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomeProtectionLead> IncomeProtectionLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InjuryClaimLeadLog> InjuryClaimLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InjuryClaimLead> InjuryClaimLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadEmailRequest> LeadEmailRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LifeLeadLog> LifeLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LifeLead> LifeLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanLeadLog> LoanLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanLead> LoanLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogBookLoanLeadLog> LogBookLoanLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogBookLoanLead> LogBookLoanLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MortgageLeadLog> MortgageLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MortgageLead> MortgageLeads { get; set; }
        public virtual OrganizationMaster OrganizationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PensionLeadLog> PensionLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PensionLead> PensionLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPILeadLog> PPILeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPILead> PPILeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrepaidFuneralLeadLog> PrepaidFuneralLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrepaidFuneralLead> PrepaidFuneralLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaster> ProductMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSlab> ProductSlabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlabDefinition> SlabDefinitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolarLeadLog> SolarLeadLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolarLead> SolarLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppressionDetail> SuppressionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Token> Tokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferLog> TransferLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebsiteMaster> WebsiteMasters { get; set; }
    }
}
